{{ $flux := index .Values "flux-core" }}
{{- range $app, $config := $flux.apps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $app }}-values"
data:
  values.yaml:
    {{- toYaml ($.Files.Get (printf "config/%s.yaml" $app)) | indent 4 }}
{{- end }}
