---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pihole-values"
  namespace: {{ $.Release.Namespace }}
data:
  values.yaml:
    {{ toYaml (.Files.Get "config/pihole.yaml") | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "nfs-values"
  namespace: {{ $.Release.Namespace }}
data:
  values.yaml:
    {{ toYaml (.Files.Get "config/nfs.yaml") | indent 4 }}
