{{ $flux := index .Values "flux-core" }}
{{- range $app, $config := $flux.apps }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $app }}-secrets"
stringData:
  secrets.yaml:
    {{- toYaml ($.Files.Get (printf "secrets/%s.yaml" $app)) | indent 4 }}
{{- end }}
