# http:
#   server_host: 0.0.0.0
#   ip_ban_enabled: true
#   login_attempts_threshold: 5
#   use_x_forwarded_for: true
#   trusted_proxies:
#   # Pod CIDR
#   - 10.42.0.0/16
#   # Node CIDR
#   - 192.168.0.0/24

image:
  tag: 2025.2.1

ingress:
  # Enable ingress for home assistant
  enabled: true
  className: traefik

  hosts:
    - host: home.192.168.1.151.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls: []

configuration:
  enabled: true

persistence:
  enabled: true
  storageClass: nfs-client
