ingress:
  # -- Setting that allows Longhorn to generate ingress records for the Longhorn UI service.
  enabled: true

  # -- IngressClass resource that contains ingress configuration, including the name of the Ingress controller.
  # ingressClassName can replace the kubernetes.io/ingress.class annotation used in earlier Kubernetes releases.
  ingressClassName: traefik

  # -- Hostname of the Layer 7 load balancer.
  host: storage.walford.io

persistence:
  defaultClassReplicaCount: 1