config: |-
  persistence true
  persistence_location /mosquitto/data/
  log_dest stdout
  listener 1884
  listener 1883
  protocol mqtt
  password_file /mosquitto/passwd
ingress:
  enabled: true
  hosts:
  - host: mqtt.walford.com
    paths:
    - /
nameOverride: mosquitto
persistence:
  enabled: false
  storageClass: nfs
replicaCount: 1
service:
  type: LoadBalancer
