apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "home-lights.fullname" . }}
  labels:
    {{- include "home-lights.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "home-lights.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "home-lights.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HUE_BRIDGE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.hueBridge.secretName }}
                  key: address
            - name: HUE_BRIDGE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.hueBridge.secretName }}
                  key: username
            - name: MQTT_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mqtt.secretName }}
                  key: address
            {{- with .Values.kasa }}
            - name: KASA_BULB_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Release.Name }}
                  key: kasa.bulbIP
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 2112
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
