replicaCount: 1

image:
  repository: adamwalford/home-lights
  pullPolicy: Always
  # tag: 0.1.0-arm64

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

hueBridge:
  secretName: hue

mqtt:
  secretName: mqtt

kasa: {}
  # bulbIP: 
