repositories:
  home:
    kind: GitRepository
    url: https://github.com/awalford16/home
    gitBranch: services

apps:
  home:
    # namespace: home
    path: .deploy/home
    type: GitRepository
    repo: home
