apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    addressPools:
      - name: default
        protocol: layer2
        addresses:
          - 192.168.0.240-192.168.0.250
