---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: activity-planner
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: activity-planner
            image: adamwalford/activity-planner:0.0.1
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
